Repository aplneto/medmapper, pull requests merged in 2019-06, with the labels that each got.

#79 desenvolvimento do fim de semana
  back_app/app/assets/stylesheets/application.scss
  back_app/app/controllers/basic_health_units_controller.rb
  back_app/app/controllers/diagnosis_units_controller.rb
  back_app/app/controllers/emergency_units_controller.rb
  back_app/app/controllers/family_health_units_controller.rb
  back_app/app/controllers/health_units_controller.rb
  back_app/app/controllers/hospitals_controller.rb
  back_app/app/controllers/maternity_clinics_controller.rb
  back_app/app/controllers/mental_health_units_controller.rb
  back_app/app/controllers/odontology_units_controller.rb
  back_app/app/controllers/pharmacies_controller.rb
  back_app/app/controllers/polyclinics_controller.rb
  back_app/app/controllers/specialized_units_controller.rb
  back_app/app/helpers/health_units_helper.rb
  back_app/app/models/professional_profile.rb
  back_app/app/views/basic_health_units/_basic_health_unit.html.slim
  back_app/app/views/basic_health_units/index.html.slim
  back_app/app/views/diagnosis_units/index.html.slim
  back_app/app/views/emergency_units/index.html.slim
  back_app/app/views/family_health_units/index.html.slim
  back_app/app/views/health_units/_form.html.slim
  back_app/app/views/health_units/_health_unit.html.slim
  back_app/app/views/health_units/edit.html.slim
  back_app/app/views/health_units/index.html.slim
  back_app/app/views/health_units/new.html.slim
  back_app/app/views/health_units/show.html.slim
  back_app/app/views/health_units/specialty.html.slim
  back_app/app/views/hospitals/_hospital.html.slim
  back_app/app/views/hospitals/index.html.slim
  back_app/app/views/hospitals/new.html.slim
  back_app/app/views/layouts/application.html.slim
  back_app/app/views/maternity_clinics/index.html.slim
  back_app/app/views/mental_health_units/index.html.slim
  back_app/app/views/odontology_units/index.html.slim
  back_app/app/views/pharmacies/index.html.slim
  back_app/app/views/polyclinics/index.html.slim
  back_app/app/views/specialized_units/index.html.slim
Labels: behaviour-test, front

#85 Apln2
  back_app/app/assets/stylesheets/application.scss
  back_app/app/controllers/pages_controller.rb
  back_app/app/controllers/user_profiles_controller.rb
  back_app/app/helpers/user_profiles_helper.rb
  back_app/app/models/user_profile.rb
  back_app/app/views/health_units/_form.html.slim
  back_app/app/views/layouts/application.html.slim
  back_app/app/views/layouts/navigation/_footer.slim
  back_app/app/views/layouts/navigation/_sidebar.slim
  back_app/app/views/pages/about.html.slim
  back_app/app/views/pages/support.html.slim
  back_app/app/views/user_profiles/_form.html.slim
  back_app/app/views/user_profiles/show.html.slim
  back_app/config/locales/pt.yml
  back_app/config/routes.rb
  back_app/db/migrate/20190605041840_add_picture_to_user_profile.rb
  back_app/db/migrate/20190605044753_create_active_storage_tables.active_storage.rb
  back_app/db/schema.rb
Labels: back, front, user-hist

#90 finalizando user profiles e views do devise / mailer
  back_app/app/controllers/comments_controller.rb
  back_app/app/controllers/user_profiles_controller.rb
  back_app/app/views/devise/confirmations/new.html.erb
  back_app/app/views/devise/confirmations/new.html.slim
  back_app/app/views/devise/mailer/confirmation_instructions.html.slim
  back_app/app/views/devise/mailer/email_changed.html.erb
  back_app/app/views/devise/mailer/email_changed.html.slim
  back_app/app/views/devise/mailer/password_change.html.erb
  back_app/app/views/devise/mailer/password_change.html.slim
  back_app/app/views/devise/mailer/reset_password_instructions.html.erb
  back_app/app/views/devise/mailer/reset_password_instructions.html.slim
  back_app/app/views/devise/mailer/unlock_instructions.html.erb
  back_app/app/views/devise/mailer/unlock_instructions.html.slim
  back_app/app/views/devise/passwords/edit.html.erb
  back_app/app/views/devise/passwords/edit.html.slim
  back_app/app/views/devise/passwords/new.html.erb
  back_app/app/views/devise/passwords/new.html.slim
  back_app/app/views/devise/registrations/edit.html.erb
  back_app/app/views/devise/registrations/edit.html.slim
  back_app/app/views/devise/registrations/new.html.erb
  back_app/app/views/devise/registrations/new.html.slim
  back_app/app/views/devise/sessions/new.html.erb
  back_app/app/views/devise/sessions/new.html.slim
  back_app/app/views/family_health_support_centers/_family_health_support_center.html.slim
  back_app/app/views/family_health_support_centers/_form.html.slim
  back_app/app/views/family_health_support_centers/edit.html.slim
  back_app/app/views/family_health_support_centers/index.html.slim
  back_app/app/views/family_health_support_centers/new.html.slim
  back_app/app/views/family_health_support_centers/show.html.slim
  back_app/app/views/user_profiles/_form.html.slim
  back_app/app/views/user_profiles/_user_profile.html.slim
  back_app/app/views/user_profiles/edit.html.slim
  back_app/app/views/user_profiles/index.html.slim
  back_app/app/views/user_profiles/new.html.slim
  back_app/app/views/user_profiles/show.html.slim
Labels: front

#93 issue 83 closed
  back_app/app/views/layouts/navigation/_sidebar.slim
  back_app/app/views/pages/home.html.slim
Labels: front

#94 Testes de comportamento (new_health_unit)
  back_app/features/add_health_unit.feature
  back_app/features/logout.feature
  back_app/features/step_definitions/add_health_unit.rb
Labels: behaviour-test, front

#98 styling
  back_app/Gemfile
  back_app/Gemfile.lock
  back_app/app/assets/images/3virgula14.png
  back_app/app/assets/images/ad-horizontal-banner.png
  back_app/app/assets/images/cin-escudo.jpg
  back_app/app/assets/images/cin.png
  back_app/app/assets/images/favicon.ico
  back_app/app/assets/images/lacaff-logo.png
  back_app/app/assets/images/user.png
  back_app/app/assets/stylesheets/application.scss
  back_app/app/assets/stylesheets/basic_health_units.scss
  back_app/app/assets/stylesheets/devise.scss
  back_app/app/assets/stylesheets/diagnosis_units.scss
  back_app/app/assets/stylesheets/emergency_units.scss
  back_app/app/assets/stylesheets/family_health_units.scss
  back_app/app/assets/stylesheets/health_units.scss
  back_app/app/assets/stylesheets/hospitals.scss
  back_app/app/assets/stylesheets/maternity_clinics.scss
  back_app/app/assets/stylesheets/mental_health_units.scss
  back_app/app/assets/stylesheets/odontology_units.scss
  back_app/app/assets/stylesheets/pharmacies.scss
  back_app/app/assets/stylesheets/polyclinics.scss
  back_app/app/assets/stylesheets/specialized_units.scss
  back_app/app/controllers/health_units_controller.rb
  back_app/app/controllers/professional_profiles_controller.rb
  back_app/app/helpers/professional_profiles_helper.rb
  back_app/app/helpers/user_profiles_helper.rb
  back_app/app/views/comments/_comment.html.slim
  back_app/app/views/devise/confirmations/new.html.slim
  back_app/app/views/devise/passwords/edit.html.slim
  back_app/app/views/devise/passwords/new.html.slim
  back_app/app/views/devise/registrations/new.html.slim
  back_app/app/views/devise/sessions/new.html.slim
  back_app/app/views/devise/shared/_links.html.erb
  back_app/app/views/family_health_support_centers/show.html.slim
  back_app/app/views/health_units/_health_unit.html.slim
  back_app/app/views/health_units/index.html.slim
  back_app/app/views/health_units/show.html.slim
  back_app/app/views/layouts/application.html.slim
  back_app/app/views/layouts/navigation/_header.slim
  back_app/app/views/layouts/navigation/_sidebar.slim
  back_app/app/views/pages/about.html.slim
  back_app/app/views/pages/collaborators.html.slim
  back_app/app/views/pages/developers.html.slim
  back_app/app/views/pages/home.html.slim
  back_app/app/views/pages/support.html.slim
  back_app/app/views/pages/terms.html.slim
  back_app/app/views/professional_profiles/index.html.slim
  back_app/app/views/user_profiles/show.html.slim
  back_app/config/i18n-tasks.yml
  back_app/config/locales/devise.pt.yml
  back_app/config/locales/pt.yml
  back_app/config/routes.rb
  back_app/spec/i18n_spec.rb
Labels: front
